"""baseline schema

The schema exactly as Base.metadata.create_all() built it before migrations were used.
Databases created that way are stamped at this revision instead of running it (app/db/migrate.py).

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-26 20:07:19.688368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('attempt_time', sa.DateTime(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_audit_id'), ['id'], unique=False)

    op.create_table('otp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_sessions_whatsapp_number'), ['whatsapp_number'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('qid', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('billing_rate', sa.Float(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('qr_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_qid'), ['qid'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_qr_token'), ['qr_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_whatsapp_number'), ['whatsapp_number'], unique=True)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_worker_id', sa.String(), nullable=False),
    sa.Column('external_employee_id', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('qid', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('face_embedding', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('qr_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_internal_worker_id'), ['internal_worker_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_qid'), ['qid'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_qr_token'), ['qr_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_whatsapp_number'), ['whatsapp_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'GENERAL_MANAGER', 'MANAGEMENT', 'OPS_MANAGER', 'HR_ADMIN', 'SUPPLIER_HEAD', 'OUTSOURCE_WORKER', 'ACCOUNTING', name='roleenum'), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('qr_status', sa.String(), nullable=True),
    sa.Column('refresh_token_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_qr_token'), ['qr_token'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('workers_supplied_quantity', sa.Integer(), nullable=False),
    sa.Column('rate_per_worker', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('document_path_pdf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_id'), ['id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geofence_radius_meters', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('qr_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_qr_token'), ['qr_token'], unique=True)

    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_devices_push_token'), ['push_token'], unique=True)

    op.create_table('manpower_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ops_manager_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('required_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('total_required_workers', sa.Integer(), nullable=False),
    sa.Column('skill_category', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ops_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manpower_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manpower_requests_id'), ['id'], unique=False)

    op.create_table('request_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manpower_request_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manpower_request_id'], ['manpower_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_messages_id'), ['id'], unique=False)

    op.create_table('supplier_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manpower_request_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Integer(), nullable=True),
    sa.Column('proposed_start_time', sa.String(), nullable=True),
    sa.Column('proposed_end_time', sa.String(), nullable=True),
    sa.Column('supplier_message', sa.Text(), nullable=True),
    sa.Column('response_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_start_time', sa.String(), nullable=True),
    sa.Column('confirmed_end_time', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manpower_request_id'], ['manpower_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_responses_id'), ['id'], unique=False)

    op.create_table('worker_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_response_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_response_id'], ['supplier_responses.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_assignments_id'), ['id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_assignment_id', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('check_in_accuracy', sa.Float(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_lat', sa.Float(), nullable=True),
    sa.Column('check_out_lng', sa.Float(), nullable=True),
    sa.Column('check_out_accuracy', sa.Float(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('face_verified', sa.Boolean(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('check_in_verification_method', sa.String(), nullable=True),
    sa.Column('check_out_verification_method', sa.String(), nullable=True),
    sa.Column('check_in_qr_id', sa.Integer(), nullable=True),
    sa.Column('check_out_qr_id', sa.Integer(), nullable=True),
    sa.Column('check_in_face_embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['check_in_qr_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['check_out_qr_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['worker_assignment_id'], ['worker_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_assignment_id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    op.create_table('attendance_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('worker_assignment_id', sa.Integer(), nullable=True),
    sa.Column('exception_type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_assignment_id'], ['worker_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_exceptions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_exceptions_id'))

    op.drop_table('attendance_exceptions')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('worker_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_assignments_id'))

    op.drop_table('worker_assignments')
    with op.batch_alter_table('supplier_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_responses_id'))

    op.drop_table('supplier_responses')
    with op.batch_alter_table('request_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_messages_id'))

    op.drop_table('request_messages')
    with op.batch_alter_table('manpower_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manpower_requests_id'))

    op.drop_table('manpower_requests')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_push_token'))
        batch_op.drop_index(batch_op.f('ix_user_devices_id'))

    op.drop_table('user_devices')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_qr_token'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))

    op.drop_table('sites')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_qr_token'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_workers_qr_token'))
        batch_op.drop_index(batch_op.f('ix_workers_qid'))
        batch_op.drop_index(batch_op.f('ix_workers_internal_worker_id'))
        batch_op.drop_index(batch_op.f('ix_workers_id'))

    op.drop_table('workers')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_suppliers_qr_token'))
        batch_op.drop_index(batch_op.f('ix_suppliers_qid'))
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('otp_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_sessions_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_otp_sessions_id'))

    op.drop_table('otp_sessions')
    with op.batch_alter_table('attendance_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_audit_id'))

    op.drop_table('attendance_audit')
    # ### end Alembic commands ###
