"""login attempts and query indexes

Revision ID: 0002_login_attempts_indexes
Revises: 0001_baseline
Create Date: 2026-09-26 20:24:51.196132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_login_attempts_indexes'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_check_in_time'), ['check_in_time'], unique=False)

    with op.batch_alter_table('manpower_requests', schema=None) as batch_op:
        batch_op.create_index('ix_manpower_requests_site_date', ['site_id', 'required_date'], unique=False)

    with op.batch_alter_table('supplier_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_responses_manpower_request_id'), ['manpower_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_responses_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('worker_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_assignments_supplier_response_id'), ['supplier_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_assignments_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_assignments_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_assignments_supplier_response_id'))

    with op.batch_alter_table('supplier_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_responses_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_responses_manpower_request_id'))

    with op.batch_alter_table('manpower_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_manpower_requests_site_date')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_check_in_time'))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
