"""supplier_mobile_updates

Revision ID: bea6162ae013
Revises: 0e5c7af7d294
Create Date: 2026-09-03 12:20:00.396220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea6162ae013'
down_revision: Union[str, None] = '0e5c7af7d294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_push_token'), 'user_devices', ['push_token'], unique=True)
    op.create_table('request_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manpower_request_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manpower_request_id'], ['manpower_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_messages_id'), 'request_messages', ['id'], unique=False)
    op.add_column('supplier_responses', sa.Column('proposed_start_time', sa.String(), nullable=True))
    op.add_column('supplier_responses', sa.Column('proposed_end_time', sa.String(), nullable=True))
    op.add_column('supplier_responses', sa.Column('supplier_message', sa.Text(), nullable=True))
    op.add_column('supplier_responses', sa.Column('response_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_responses', 'response_type')
    op.drop_column('supplier_responses', 'supplier_message')
    op.drop_column('supplier_responses', 'proposed_end_time')
    op.drop_column('supplier_responses', 'proposed_start_time')
    op.drop_index(op.f('ix_request_messages_id'), table_name='request_messages')
    op.drop_table('request_messages')
    op.drop_index(op.f('ix_user_devices_push_token'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_table('user_devices')
    # ### end Alembic commands ###
