"""ops_finalize_fields

Revision ID: f024299e38e4
Revises: bea6162ae013
Create Date: 2026-09-07 10:28:20.109222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f024299e38e4'
down_revision: Union[str, None] = 'bea6162ae013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_responses', sa.Column('confirmed_start_time', sa.String(), nullable=True))
    op.add_column('supplier_responses', sa.Column('confirmed_end_time', sa.String(), nullable=True))
    op.add_column('supplier_responses', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('supplier_responses', sa.Column('confirmed_by_id', sa.Integer(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_responses', type_='foreignkey')
    op.drop_column('supplier_responses', 'confirmed_by_id')
    op.drop_column('supplier_responses', 'confirmed_at')
    op.drop_column('supplier_responses', 'confirmed_end_time')
    op.drop_column('supplier_responses', 'confirmed_start_time')
    # ### end Alembic commands ###
